-- =============================================================
-- Migração: Criação da tabela BRSACC_NPS
-- Executar manualmente no Oracle antes de usar o endpoint de NPS.
-- =============================================================

-- Substitua {OWNER} pelo schema correto (ex: BRAVO)

CREATE TABLE {OWNER}.BRSACC_NPS (
  ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NUMTICKET  NUMBER        NOT NULL,
  CODCLI     NUMBER        NOT NULL,
  SCORE      NUMBER(2)     NOT NULL CHECK (SCORE BETWEEN 0 AND 10),
  FEEDBACK   VARCHAR2(1000),
  DTCRIACAO  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

-- Índice para busca rápida por ticket + cliente
CREATE INDEX {OWNER}.IDX_BRSACC_NPS_TICKET_CLI 
  ON {OWNER}.BRSACC_NPS (NUMTICKET, CODCLI);

-- Constraint para impedir avaliação duplicada de um mesmo ticket por cliente
ALTER TABLE {OWNER}.BRSACC_NPS 
  ADD CONSTRAINT UQ_BRSACC_NPS_TICKET_CLI UNIQUE (NUMTICKET, CODCLI);
